// Generated by typings
// Source: node_modules/postcss-middleware/dist/lib/middleware.d.ts
declare module 'middleware' {
function PostCssMiddleware(options?: PostCssMiddleware.Options): (req: any, res: any, next: Function) => void;
module PostCssMiddleware {
    interface Options {
        /**
         * An array of PostCSS plugins.
         */
        plugins: Function[];
        /**
         * PostCSS options
         */
        options?: Object;
        /**
         * Build the file path to the source file(s) you wish to read.
         */
        src?: 
        /**
         * @param request The Express app's request object.
         * @returns A glob string or an array of glob strings. All files matched
         * will be concatenated in the response.
         */
        (request: any) => string | string[];
        /**
         * Generate inlined sourcemaps.
         */
        inlineSourcemaps?: boolean;
    }
}
export = PostCssMiddleware;
}
