// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/bad2560a5487921a2699e1a7db2a8878e6c4e11c/node-sass-middleware/node-sass-middleware.d.ts
declare module "node-sass-middleware" {

    import * as sass from "node-sass";
    import * as express from "express";

    interface Options extends sass.Options {
        /**
         * 
         */
        src: string;
        /**
         * 
         */
        dest?: string;
        /**
         * 
         */
        root?: string;
        /**
         * 
         */
        prefix?: string;
        /**
         * 
         */
        force?: boolean;
        /**
         * 
         */
        debug?: boolean;
        /**
         * 
         */
        indentedSyntax?: boolean;
        /**
         * 
         */
        response?: boolean;
        /**
         * 
         */
        error?: () => void;
    }

    /**
     * 
     *
     */

    function nodeSassMiddleware(options: Options): express.RequestHandler;

    /**
     * 
     */
    namespace nodeSassMiddleware { }

    /**
     * 
     */
    export = nodeSassMiddleware;
}
